=== Bainbridge-Growth/airbyte/airbyte-integrations/connectors/source-quickbooks-drivepoint/source_quickbooks_drivepoint/schemas/transaction_list.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "TxDate": {
      "type": ["null", "string"],
      "format": "date-time"
    },
    "TransactionType": {
      "type": ["null", "string"]
    },
    "TransactionTypeId": {
      "type": ["null", "string"]
    },
    "DocNum": {
      "type": ["null", "string"]
    },
    "Posting": {
      "type": ["null", "string"]
    },
    "Name": {
      "type": ["null", "string"]
    },
    "NameId": {
      "type": ["null", "string"]
    },
    "Department": {
      "type": ["null", "string"]
    },
    "DepartmentId": {
      "type": ["null", "string"]
    },
    "Memo": {
      "type": ["null", "string"]
    },
    "Account": {
      "type": ["null", "string"]
    },
    "AccountId": {
      "type": ["null", "string"]
    },
    "Split": {
      "type": ["null", "string"]
    },
    "SplitId": {
      "type": ["null", "string"]
    },
    "Amount": {
      "type": ["null", "string"]
    },
    "StartPeriod": {
      "type": ["null", "string"],
      "format": "date-time"
    },
    "EndPeriod": {
      "type": ["null", "string"],
      "format": "date-time"
    },
    "Currency": {
      "type": ["null", "string"]
    },
    "_airbyte_emitted_at": {
      "type": ["null", "string"],
      "format": "date-time"
    }
  }
}

=== Bainbridge-Growth/airbyte/airbyte-integrations/connectors/source-quickbooks-drivepoint/unit_tests/resources/expected_results/transaction_list_subt_nat_amount.json
[
  {
    "TxDate": "2026-01-01T00:00:00Z",
    "TransactionType": "Expense",
    "TransactionTypeId": "33256",
    "DocNum": "",
    "Posting": "Yes",
    "Name": "Amazon Business",
    "NameId": "3",
    "Department": "",
    "DepartmentId": "",
    "Memo": "Amazon; AMAZON.COM",
    "Account": "2103 Mercury Credit Card",
    "AccountId": "320",
    "Split": "6133 Marketing Expenses:Growth Marketing:Amazon Media",
    "SplitId": "351",
    "Amount": "501.85",
    "StartPeriod": "2026-01-01T00:00:00Z",
    "EndPeriod": "2026-01-31T00:00:00Z",
    "Currency": "USD"
  },
  {
    "TxDate": "2026-01-27T00:00:00Z",
    "TransactionType": "Invoice",
    "TransactionTypeId": "33860",
    "DocNum": "INV6583873",
    "Posting": "Yes",
    "Name": "UNFI",
    "NameId": "4653",
    "Department": "",
    "DepartmentId": "",
    "Memo": "",
    "Account": "1100 Accounts receivable (A/R)",
    "AccountId": "8",
    "Split": "-Split-",
    "SplitId": "",
    "Amount": "32659.20",
    "StartPeriod": "2026-01-01T00:00:00Z",
    "EndPeriod": "2026-01-31T00:00:00Z",
    "Currency": "USD"
  }
]

=== Bainbridge-Growth/airbyte/airbyte-integrations/connectors/source-quickbooks-drivepoint/unit_tests/resources/expected_results/transaction_list_simple.json
[
  {
    "TxDate": "2016-06-14T00:00:00Z",
    "TransactionType": "Invoice",
    "TransactionTypeId": "151",
    "DocNum": "1040",
    "Posting": "Yes",
    "Name": "Amy's Bird Sanctuary",
    "NameId": "1",
    "Department": "West Coast",
    "DepartmentId": "1",
    "Memo": "This is a private note.",
    "Account": "Accounts Receivable (A/R)",
    "AccountId": "84",
    "Split": "-Split-",
    "SplitId": "",
    "Amount": "47.60",
    "StartPeriod": "2016-06-01T00:00:00Z",
    "EndPeriod": "2016-07-31T00:00:00Z",
    "Currency": "USD"
  },
  {
    "TxDate": "2016-06-14T00:00:00Z",
    "TransactionType": "Payment",
    "TransactionTypeId": "153",
    "DocNum": "3456",
    "Posting": "Yes",
    "Name": "Amy's Bird Sanctuary",
    "NameId": "1",
    "Department": "West Coast",
    "DepartmentId": "1",
    "Memo": "",
    "Account": "Checking",
    "AccountId": "35",
    "Split": "Accounts Receivable (A/R)",
    "SplitId": "84",
    "Amount": "45.00",
    "StartPeriod": "2016-06-01T00:00:00Z",
    "EndPeriod": "2016-07-31T00:00:00Z",
    "Currency": "USD"
  },
  {
    "TxDate": "2016-06-14T00:00:00Z",
    "TransactionType": "Invoice",
    "TransactionTypeId": "154",
    "DocNum": "1041",
    "Posting": "Yes",
    "Name": "Amy's Bird Sanctuary",
    "NameId": "1",
    "Department": "",
    "DepartmentId": "",
    "Memo": "",
    "Account": "Accounts Receivable (A/R)",
    "AccountId": "84",
    "Split": "Design income",
    "SplitId": "82",
    "Amount": "375.00",
    "StartPeriod": "2016-06-01T00:00:00Z",
    "EndPeriod": "2016-07-31T00:00:00Z",
    "Currency": "USD"
  },
  {
    "TxDate": "2016-06-20T00:00:00Z",
    "TransactionType": "Credit Memo",
    "TransactionTypeId": "155",
    "DocNum": "1042",
    "Posting": "Yes",
    "Name": "Amy's Bird Sanctuary",
    "NameId": "1",
    "Department": "West Coast",
    "DepartmentId": "1",
    "Memo": "",
    "Account": "Accounts Receivable (A/R)",
    "AccountId": "84",
    "Split": "Sales of Product Income",
    "SplitId": "79",
    "Amount": "-16.20",
    "StartPeriod": "2016-06-01T00:00:00Z",
    "EndPeriod": "2016-07-31T00:00:00Z",
    "Currency": "USD"
  },
  {
    "TxDate": "2016-06-21T00:00:00Z",
    "TransactionType": "Invoice",
    "TransactionTypeId": "160",
    "DocNum": "1045",
    "Posting": "Yes",
    "Name": "Amy's Bird Sanctuary",
    "NameId": "1",
    "Department": "",
    "DepartmentId": "",
    "Memo": "",
    "Account": "Accounts Receivable (A/R)",
    "AccountId": "84",
    "Split": "-Split-",
    "SplitId": "",
    "Amount": ".00",
    "StartPeriod": "2016-06-01T00:00:00Z",
    "EndPeriod": "2016-07-31T00:00:00Z",
    "Currency": "USD"
  },
  {
    "TxDate": "2016-07-28T00:00:00Z",
    "TransactionType": "Sales Receipt",
    "TransactionTypeId": "161",
    "DocNum": "1046",
    "Posting": "Yes",
    "Name": "Amy's Bird Sanctuary",
    "NameId": "1",
    "Department": "",
    "DepartmentId": "",
    "Memo": "",
    "Account": "Checking",
    "AccountId": "35",
    "Split": "Landscaping Services:Job Materials:Fountains and Garden Lighting",
    "SplitId": "48",
    "Amount": "54.55",
    "StartPeriod": "2016-06-01T00:00:00Z",
    "EndPeriod": "2016-07-31T00:00:00Z",
    "Currency": "USD"
  },
  {
    "TxDate": "2016-06-20T00:00:00Z",
    "TransactionType": "Credit Memo",
    "TransactionTypeId": "157",
    "DocNum": "1043",
    "Posting": "Yes",
    "Name": "Bill's Windsurf Shop",
    "NameId": "2",
    "Department": "West Coast",
    "DepartmentId": "1",
    "Memo": "",
    "Account": "Accounts Receivable (A/R)",
    "AccountId": "84",
    "Split": "Sales of Product Income",
    "SplitId": "79",
    "Amount": "-16.20",
    "StartPeriod": "2016-06-01T00:00:00Z",
    "EndPeriod": "2016-07-31T00:00:00Z",
    "Currency": "USD"
  },
  {
    "TxDate": "2016-06-21T00:00:00Z",
    "TransactionType": "Invoice",
    "TransactionTypeId": "159",
    "DocNum": "1044",
    "Posting": "Yes",
    "Name": "Cool Cars",
    "NameId": "3",
    "Department": "West Coast",
    "DepartmentId": "1",
    "Memo": "",
    "Account": "Accounts Receivable (A/R)",
    "AccountId": "84",
    "Split": "-Split-",
    "SplitId": "",
    "Amount": ".00",
    "StartPeriod": "2016-06-01T00:00:00Z",
    "EndPeriod": "2016-07-31T00:00:00Z",
    "Currency": "USD"
  }
]
